// action fetch data
export const FETCH_POLLS_REQUEST = 'FETCH_POLLS_REQUEST'
export const FETCH_POLLS_SUCCESS = 'FETCH_POLLS_SUCCESS'
export const FETCH_POLLS_FAILURE = 'FETCH_POLLS_FAILURE'

// action Delete
export const DELETE_POLL_REQUEST = 'DELETE_POLL_REQUEST'
export const DELETE_POLL_SUCCESS = 'DELETE_POLL_SUCCESS'
export const DELETE_POLL_FAILURE = 'DELETE_POLL_FAILURE'

// action add data
export const ADD_POLL_REQUEST = 'ADD_POLL_REQUEST'
export const ADD_POLL_SUCCESS = 'ADD_POLL_SUCCESS'
export const ADD_POLL_FAILURE = 'ADD_POLL_FAILURE'
